import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';

const cwd = process.cwd();
function readEnvFile(file) {
  const full = path.join(cwd, file);
  if (!fs.existsSync(full)) return {};
  const out = {};
  for (const raw of fs.readFileSync(full, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const i = line.indexOf('=');
    if (i < 0) continue;
    const key = line.slice(0, i).trim();
    let value = line.slice(i + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    out[key] = value;
  }
  return out;
}
const env = { ...readEnvFile('.env'), ...process.env };
const url = env.PUBLIC_SUPABASE_URL;
const key = env.PUBLIC_SUPABASE_PUBLISHABLE_KEY || env.PUBLIC_SUPABASE_ANON_KEY;
if (!url || !key) {
  console.error('Missing PUBLIC_SUPABASE_URL / PUBLIC_SUPABASE_PUBLISHABLE_KEY in .env');
  process.exit(1);
}
const supabase = createClient(url, key, { auth: { persistSession: false } });
const { data, error } = await supabase.from('seo_pages').select('*').order('path');
if (error) {
  console.error('SEO sync failed:', error.message);
  console.error('Run supabase/seo-management.sql first.');
  process.exit(1);
}
const normalize = p => {
  if (!p) return '/';
  const clean = String(p).split('?')[0].split('#')[0];
  return clean === '/' ? '/' : `/${clean.replace(/^\/+|\/+$/g, '')}/`;
};
const entries = {};
for (const row of data || []) {
  entries[normalize(row.path)] = {
    title: row.seo_title || undefined,
    description: row.meta_description || undefined,
    focusKeyword: row.focus_keyword || undefined,
    canonicalUrl: row.canonical_url || undefined,
    index: row.index_enabled !== false,
    schemaType: row.schema_type || undefined,
    ogTitle: row.og_title || undefined,
    ogDescription: row.og_description || undefined,
    ogImage: row.og_image || undefined,
  };
}
const content = `// AUTO-GENERATED by \`npm run seo:sync\`.\n// Do not edit manually; manage records from /admin > SEO Yönetimi.\nexport type SeoAdminOverride = {\n  title?: string;\n  description?: string;\n  focusKeyword?: string;\n  canonicalUrl?: string;\n  index?: boolean;\n  schemaType?: string;\n  ogTitle?: string;\n  ogDescription?: string;\n  ogImage?: string;\n};\n\nexport const seoAdminOverrides: Record<string, SeoAdminOverride> = ${JSON.stringify(entries, null, 2)};\n`;
const target = path.join(cwd, 'src/data/seoAdmin.generated.ts');
fs.writeFileSync(target, content, 'utf8');
console.log(`SEO sync complete: ${Object.keys(entries).length} page override(s) written.`);
